#端口配置
server:
  port: 9520

#springboot项目的配置文件
spring:
  webservices:
    path: /test
  ##数据库连接的相关配置信息
  datasource:
    #简写版
    url: jdbc:mysql://localhost:3306/ctwokm?characterEncoding=utf8&serverTimezone=GMT%2B8
    #完整版，各种限定
    #url: jdbc:mysql://localhost:3306/ctwokm?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: admin
  jpa:
    #选择的数据库
    database: mysql
    #是否显示sql语句
    show-sql: true
    #Hibernate ddl auto (validate|create|create-drop|update)
    #create：每次运行程序时，都会重新创建表，故而数据会丢失
    #create-drop：每次运行程序时会先创建表结构，然后待程序结束时清空表
    #upadte：每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新（推荐使用）
    #validate：运行程序会校验数据与数据库的字段类型是否相同，字段不同会报错
    #none: 禁用DDL处理
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  ##redis的配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    #如果没有密码就直接不要写password，否则会报错
    password: 123456
    #连接超时时间（毫秒）
    timeout: 3000ms
    jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 512
          # 连接池中的最大空闲连接 默认 8
          max-idle: 100
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0
          # 连接池最大阻塞等待时间,单位毫秒（使用负值表示没有限制） 默认 -1
          max-wait: -1ms
    